name: steric-descriptors-alcohol
channels:
  - conda-forge
dependencies:
  - joblib=1.4.2
  - jupyter=1.1.1
  - matplotlib=3.8.4
  - morfeus-ml=0.7.2
  - numpy=1.26.4
  - pandas=2.2.2
  - python=3.11.9
  - rdkit=2024.03.1
  - scikit-learn=1.4.2
  - seaborn=0.13.2
